# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e3b1865d667737b531c56155a5132c4408be3a4070553464d8695823e0f4786544f087c8afcd1006678be03e9a382bfdf18ba3cd204e9300cf87f16de646076d

test:
  secret_key_base: 0e55e48692998f48d6a782af685055d3902826fa4c755a2b86bbad0497240c260faa4aa7f70119e3aa69cd5197977411a36f4494303fdc873bc01101624a97fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
